import YoungDiagram.ListAux
import YoungDiagram.Gene
import YoungDiagram.Chromosome
import YoungDiagram.Variety
import YoungDiagram.Mutations
import YoungDiagram.Lifting
import YoungDiagram.Sigma
import YoungDiagram.Theorem6
import YoungDiagram.Theorem6.decomp_pi
